fragment ActivityBlockFragment on ComponentContentBlocksActivitiesBlock {
  title: activitiesTitle
  initialItems: activitiesInitialItems
  blockProperties: activitiesBlockProperties {
    variant
    orientation
    slug
  }
}
