fragment CalendarBlockFragment on ComponentContentBlocksCalendarBlock {
  calendarTitle
  calendarBlockProperties {
    variant
    orientation
    slug
  }
  cta: calendarCallToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
