fragment CalendarBlockFragment on ComponentContentBlocksCalendarBlock {
  title: calendarTitle
  blockProperties: calendarBlockProperties {
    variant
    orientation
    slug
  }
  cta: calendarCallToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
