fragment EventsBlockFragment on ComponentContentBlocksEventsBlock {
  blockTitle: eventsTitle
  initialItems: eventsInitialItems
  blockProperties: eventsBlockProperties {
    variant
    orientation
    slug
  }
}
