fragment FAQBlockFragment on ComponentContentBlocksFaqBlock {
  faqTitle
  faqBottomText
  faqItems {
    documentId
    question
    answer
    image {
      ...ImageFragment
    }
    callToAction {
      label
      link
      variant
    }
  }
  faqBlockProperties {
    variant
    orientation
    slug
  }
}
