fragment FAQBlockFragment on ComponentContentBlocksFaqBlock {
  title: faqTitle
  bottomText: faqBottomText
  faqItems {
    documentId
    question
    answer
    image {
      ...ImageFragment
    }
    callToAction {
      label
      link
      variant
    }
  }
  blockProperties: faqBlockProperties {
    variant
    orientation
    slug
  }
}
