fragment GalleryBlockFragment on ComponentContentBlocksGalleryBlock {
  title
  initialItems
  images {
    ...ImageFragment
  }
  cta: callToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
  blockProperties {
    variant
    orientation
    slug
  }
}
