fragment GalleryBlockFragment on ComponentContentBlocksGalleryBlock {
  title: galleryTitle
  initialItems: galleryInitialItems
  images: galleryImages {
    ...ImageFragment
  }
  cta: galleryCallToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
  blockProperties: galleryBlockProperties {
    variant
    orientation
    slug
  }
}
