fragment GalleryBlockFragment on ComponentContentBlocksGalleryBlock {
  galleryTitle
  galleryInitialItems
  galleryImages {
    ...ImageFragment
  }
  cta: galleryCallToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
  galleryBlockProperties {
    variant
    orientation
    slug
  }
}
