fragment GroupsBlockFragment on ComponentContentBlocksGroupsBlock {
  title: groupsTitle
  groups: groupsItems {
    documentId
    name
    slug
    logo {
      ...ImageFragment
    }
  }
  blockProperties: groupsBlockProperties {
    variant
    orientation
    slug
  }
  cta: groupsCallToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
