fragment GroupsBlockFragment on ComponentContentBlocksGroupsBlock {
  title
  groups {
    documentId
    name
    slug
    logo {
      ...ImageFragment
    }
  }
  blockProperties {
    variant
    orientation
    slug
  }
  cta: callToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
