fragment GroupsBlockFragment on ComponentContentBlocksGroupsBlock {
  groupsTitle
  groupsItems {
    documentId
    name
    slug
    logo {
      ...ImageFragment
    }
  }
  groupsBlockProperties {
    variant
    orientation
    slug
  }
  cta: groupsCallToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
