fragment HeroBlockFragment on ComponentContentBlocksHeroBlock {
  title: heroTitle
  subtitle: heroSubtitle
  variant: heroVariant
  callToAction: heroCta {
    label
    link
    variant
  }
  socialsCta: heroSocialsCta {
    title
    socialItems {
      documentId
      title
      link
      icon
    }
  }
  yearTheme: heroYearTheme {
    documentId
    title
    image {
      ...ImageFragment
    }
  }
  bgImage: heroBgImage {
    ...ImageFragment
  }
}
