fragment HeroBlockFragment on ComponentContentBlocksHeroBlock {
  heroTitle
  heroSubtitle
  heroVariant
  heroCta {
    label
    link
    variant
  }
  heroSocialsCta {
    title
    socialItems {
      documentId
      title
      link
      icon
    }
  }
  heroYearTheme {
    documentId
    title
    image {
      ...ImageFragment
    }
  }
  heroBgImage {
    ...ImageFragment
  }
}
