fragment LeadersBlockFragment on ComponentContentBlocksLeadersBlock {
  title: leadersTitle
  blockProperties: leadersBlockProperties {
    variant
    orientation
    slug
  }
  cta: leadersCallToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
