fragment MapBlockFragment on ComponentContentBlocksMapBlock {
  title: mapTitle
  location: mapLocation
  query: mapQuery
  blockProperties: mapBlockProperties {
    variant
    orientation
    slug
  }
}
