fragment NavigationItemFragment on NavigationItem {
  title
  type
  path
  externalPath
  menuAttached
  related {
    ... on Group {
      description
    }
    ... on RentalLocation {
      description
    }
  }
  items {
    title
    type
    path
    externalPath
    menuAttached
    related {
      ... on Group {
        description
      }
      ... on RentalLocation {
        description
      }
    }
    items {
      title
      type
      path
      externalPath
      menuAttached
      related {
        ... on Group {
          description
        }
        ... on RentalLocation {
          description
        }
      }
    }
  }
}
