fragment PageMetaFragment on ComponentGeneralPageMeta {
  pageTitle
  pageDescription
  noIndex
  metaImage {
    ...ImageFragment
  }
  metaSocial {
    socialNetwork
    title
    description
    image {
      ...ImageFragment
    }
  }
}
