fragment TarifsBlockFragment on ComponentContentBlocksTarifsBlock {
  tarifsTitle
  tarifsItems {
    documentId
    name
    minimumPrice
    dayPrice
    example
  }
  tarifsBlockProperties {
    variant
    orientation
    slug
  }
  cta: tarifsCallToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
