fragment TarifsBlockFragment on ComponentContentBlocksTarifsBlock {
  title: tarifsTitle
  tarifs: tarifsItems {
    documentId
    name
    minimumPrice
    dayPrice
    example
  }
  blockProperties: tarifsBlockProperties {
    variant
    orientation
    slug
  }
  cta: tarifsCallToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
