fragment TextImageBlockFragment on ComponentContentBlocksTextImageBlock {
  title: textImageTitle
  content: textImageContent
  orientation: textImageLayout
  images: textImageImages {
    ...ImageFragment
  }
  ctaButton: textImageCtaButton {
    label
    link
    variant
  }
  blockProperties: textImageBlockProperties {
    variant
    orientation
    slug
  }
}
