fragment TextImageBlockFragment on ComponentContentBlocksTextImageBlock {
  textImageTitle
  textImageContent
  orientation: textImageLayout
  textImageImages {
    ...ImageFragment
  }
  textImageCtaButton {
    label
    link
    variant
  }
  textImageBlockProperties {
    variant
    orientation
    slug
  }
}
