fragment YearThemeBlockFragment on ComponentContentBlocksYearThemeBlock {
  yearThemeTitle
  yearThemeBlockProperties {
    variant
    orientation
    slug
  }
  cta: yearThemeCallToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
