fragment YearThemeBlockFragment on ComponentContentBlocksYearThemeBlock {
  title: yearThemeTitle
  blockProperties: yearThemeBlockProperties {
    variant
    orientation
    slug
  }
  cta: yearThemeCallToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
